config/routes.rb
Rails.application.routes.draw do
  get 'home_page/index'
  devise_for :users
  resources :produtos


  post 'produtos/comprar/:id', to: 'produtos#comprar', as: 'comprar_produto'
  post 'produtos/vender/:id', to: 'produtos#vender', as: 'vender_produto'
  #root 'produtos#index'
  root 'home_page#index'

  #adiciona e remove itens do quadrinho
  post 'produtos/adicionar_ao_carrinho/:id', to: 'produtos#adicionar_ao_carrinho', as: 'adicionar_ao_carrinho'
  delete 'produtos/remover_do_carrinho/:id', to: 'produtos#remover_do_carrinho', as: 'remover_do_carrinho'

  get 'carrinho', to: 'produtos#carrinho', as: 'carrinho'
  get 'historico_vendas', to: 'produtos#historico_vendas', as: 'historico_vendas'
  post 'finalizar_venda', to: 'produtos#finalizar_venda', as: 'finalizar_venda'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/carrinho.rb
class Carrinho < ApplicationRecord
  belongs_to :user
  has_many :carrinho_itens, dependent: :destroy, class_name: 'CarrinhoItem'
end

app/models/carrinho_item.rb
class CarrinhoItem < ApplicationRecord
  belongs_to :carrinho, class_name: 'Carrinho'
  belongs_to :produto
end

app/models/carteira.rb
class Carteira < ApplicationRecord
  belongs_to :user
end

app/models/produto.rb
class Produto < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord

  has_one :carteira
  has_one :carrinho

  has_many :vendas

  #after_create :create_carteira

  private

    def create_carteira
      # Cria uma carteira associada a este usuário
      self.build_carteira(saldo: 0.0)
    end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/venda.rb
class Venda < ApplicationRecord
  belongs_to :user
  belongs_to :produto
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  def index
  end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
    before_action :authenticate_user!
    def index
      @produtos = Produto.all
      @users = User.all
      #@carrinhos = Carrinho.all
    end

    def new
        @produto = Produto.new
    end

    def create
        @produto = Produto.new(produto_params)

        if @produto.save
            redirect_to root_path
        else
            render :new, status: :unprocessable_entity
        end
      
    end
  
    def comprar
        produto = Produto.find(params[:id])
        quantidade_comprada = params[:produto][:quantidade].to_i
  
        produto.update(quantidade: produto.quantidade + quantidade_comprada)
        flash[:notice] = "Produto comprado com sucesso!"
        
        redirect_to produtos_path
      end
  
    def vender
        #venda do produto e atualiza a quantiade
        produto = Produto.find(params[:id])
        quantidade_vendida = params[:produto][:quantidade].to_i
        produto.update(quantidade: produto.quantidade - quantidade_vendida)
        flash[:notice] = "Produto vendido com sucesso!"


        #adiciona o valor vendido no saldo do usuario logado
        user = current_user
        carteira = user.carteira
        valor_venda = produto.preco * quantidade_vendida
        carteira.update(saldo: carteira.saldo + valor_venda)


        # Suponha que o usuário tenha uma carteira onde o valor seja armazenado.
        # Você pode adicionar lógica para atualizar a carteira do usuário aqui.
        redirect_to produtos_path
    end
    
    def adicionar_ao_carrinho
        produto = Produto.find(params[:id])
        quantidade_adicionada = params[:produto][:quantidade].to_i
        carrinho = current_user.carrinho

        #verificia se exise senao cria e adiciona a quantidade


        carrinho_item = carrinho.carrinho_itens.find_or_initialize_by(produto_id: produto.id)
        if carrinho_item.nil?
            carrinho_item = CarrinhoItem.new(carrinho: carrinho, produto: produto, quantidade: quantidade_adicionada)
            carrinho_item.save
            carrinho_item.quantidade = carrinho_item.quantidade + quantidade_adicionada
        else
            carrinho_item.quantidade = carrinho_item.quantidade + quantidade_adicionada
        end
        
            
        
       
        

        if carrinho_item.save
            flash[:notice] = "Produto adicionado ao carrinho."
        else
            flash[:alert] = "Erro ao adicionar o produto ao carrinho."
        end
        
        redirect_to produtos_path
    end

    def remover_do_carrinho
        carrinho_item = CarrinhoItem.find(params[:id])

        if carrinho_item.destroy
        flash[:notice] = "Produto removido do carrinho."
        else
        flash[:alert] = "Erro ao remover o produto do carrinho."
        end
        redirect_to produtos_path
    end

    def destroy
        produto = Produto.find(params[:id]) 
        produto.destroy
        redirect_to produtos_path
    end

    def finalizar_venda
        carrinho = current_user.carrinho
        carrinho.carrinho_itens.each do |carrinho_item|
            venda = Venda.new(user: current_user, produto: carrinho_item.produto, quantidade: carrinho_item.quantidade, data: Time.now)
            venda.save
            carrinho_item.destroy
        end

        flash[:notice] = "venda finalizada com sucesso."
        redirect_to produtos_path
    end

    def historico_vendas
        @vendas = current_user.vendas
      
    end

    private
        def produto_params
            params.require(:produto).permit(:nome,:quantidade,:preco)
          
        end

end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/home_page/index.html.erb
<h1>Bem vindo a madereira ideal</h1>

<p>Aqui a madeira é barato!!</p>

<%= link_to 'Fazer uma Compra', produtos_path %>
<hr>
<%= link_to 'Fazer uma Venda', produtos_path %>
<hr>
<%= link_to 'Historico de vendas', produtos_path %>
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Controle</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= link_to 'Homepage', home_page_index_path %>
    <%= yield %>
  </body>
</html>

app/views/produtos/carrinho.html.erb
<h1>Carrinho de Compras</h1>
<%= link_to 'voltar para produtos', produtos_path%>
<% if flash[:notice] %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>

<table>
  <thead>
    <tr>
      <th>Produto</th>
      <th>Quantidade</th>
      <th>Preço</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    <% current_user.carrinho.carrinho_itens.each do |carrinho_item| %>
      <tr>
        <td><%= carrinho_item.produto.nome %></td>
        <td><%= carrinho_item.quantidade %></td>
        <td><%= number_to_currency(carrinho_item.produto.preco) %></td>
        <td>
          <%= link_to 'Remover do Carrinho', remover_do_carrinho_path(carrinho_item), method: :delete, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/produtos/historico_compras.html.erb
<h1>Histórico de vendas</h1>

<table>
  <thead>
    <tr>
      <th>Produto</th>
      <th>Quantidade</th>
      <th>Preço</th>
      <th>Data</th>
    </tr>
  </thead>
  <tbody>
    <% current_user.vendas.each do |venda| %>
      <tr>
        <td><%= venda.produto.nome %></td>
        <td><%= venda.quantidade %></td>
        <td><%= number_to_currency(venda.produto.preco) %></td>
        <td><%= venda.data.strftime('%d/%m/%Y %H:%M') %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/produtos/index.html.erb
<h1>Controle de Estoque</h1>

<hr>
<%= link_to "Carrinho", carrinho_path %>
<hr>

<% if user_signed_in? %> 
  <hr>
 <div> Welcome <%= current_user.email %> </div> 
 <div> Carteira <%= @users.first.carteira.saldo %> </div> 
  <hr>
  <%= button_to "Sign out", destroy_user_session_path, method: :delete %> 
  <hr>
<% else %>
  <hr>
  <%= button_to "Sign in", new_user_session_path %> 
    <hr>
<% end %>





<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Quantidade</th>
      <th>Preço</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @produtos.each do |produto| %>
      <tr>
        <td><%= produto.nome %></td>
        <td><%= produto.quantidade %></td>
        <td><%= number_to_currency(produto.preco) %></td>
        <td>
           <hr>

            <%= form_for produto, url: vender_produto_path(produto), method: :post, class: 'vender-form' do |f| %>
                <div class="field">
                <%= f.label :quantidade %>
                <%= f.number_field :quantidade, class: 'form-control' %>
                </div>
                <%= f.submit 'vender', class: 'btn btn-primary' %>
            <% end %>
           
          
            <%= form_for produto, url: comprar_produto_path(produto), method: :post, class: 'comprar-form' do |f| %>
                <div class="field">
                <%= f.label :quantidade %>
                <%= f.number_field :quantidade, class: 'form-control' %>
                </div>
                <%= f.submit 'Comprar', class: 'btn btn-primary' %>
            <% end %>

            <%= form_for produto, url: adicionar_ao_carrinho_path(produto), method: :post, class: 'adicionar-ao-carrinho-form' do |f| %>
              <div class="field">
                <%= f.label :quantidade %>
                <%= f.number_field :quantidade, class: 'form-control' %>
              </div>
              <%= f.submit 'Adicionar ao Carrinho', class: 'btn btn-primary' %>
            <% end %>

            <%= link_to "Destroy", produto_path(produto), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New produto", new_produto_path %>

app/views/produtos/new.html.erb
<h1>New produto</h1>

<%= form_with model: @produto do |form| %>
  <div>
    <%= form.label :nome %><br>
    <%= form.text_field :nome %>
    <% @produto.errors.full_messages_for(:nome).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :quantidade %><br>
    <%= form.text_area :quantidade %><br>
    <% @produto.errors.full_messages_for(:quantidade).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :preco %><br>
    <%= form.text_area :preco %><br>
    <% @produto.errors.full_messages_for(:preco).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>